# Generated by Django 5.1.7 on 2025-03-28 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolfee',
            options={'ordering': ['-academic_year', 'semester']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='accommodation',
            name='hall_of_residence',
            field=models.CharField(default='Main Campus', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='academic_year',
            field=models.CharField(default='2025', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='due_date',
            field=models.DateField(default='2025-03-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='semester',
            field=models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('summer', 'Summer Semester')], default='1st', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='student_portal.student'),
        ),
        migrations.AlterField(
            model_name='schoolfee',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schoolfee',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial Payment'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_fees', to='student_portal.student'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolfee',
            unique_together={('student', 'academic_year', 'semester')},
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='student_portal.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('school_fee', 'School Fee'), ('accommodation', 'Accommodation'), ('deposit', 'Deposit'), ('other', 'Other')], max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('school_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='student_portal.schoolfee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='student_portal.student')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date'],
            },
        ),
    ]
