# Generated by Django 5.1.7 on 2025-03-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_alter_schoolfee_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfee',
            name='due_date',
            field=models.DateField(default='2025-03-10'),
        ),
    ]
