# Generated by Django 5.1.7 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0003_alter_schoolfee_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
