# Generated by Django 5.1.7 on 2025-03-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0005_fix_date_formats'),
    ]

    operations = [
    ]
