# Generated by Django 5.1.7 on 2025-03-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0007_alter_schoolfee_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
