# Generated by Django 5.1.7 on 2025-03-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0008_accommodation_amount_paid'),
    ]

    operations = [
    ]
