# Generated by Django 5.1.7 on 2025-03-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0013_fix_school_fee_payments'),
    ]

    operations = [
    ]
