# Generated by Django 5.1.7 on 2025-03-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0020_fix_school_fee_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
