# Generated by Django 5.1.7 on 2025-03-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0021_schoolfee_amount_paid'),
    ]

    operations = [
    ]
